---
 - hosts: all
   vars:
     - opsauto_password: '$1$ev9SIPmK$SnV2RWhWw7L36Xhpf5Ia9.'
   gather_facts: no
   become: true
   tasks:
   - name: Add a new user named opsauto
     user:
          name: opsauto
          shell: /bin/bash
          home: /home/opsauto
          password: "{{ opsauto_password }}"
   - name: Add opsauto user to the sudoers
     copy:
          dest: "/etc/sudoers.d/opsauto"
          content: "opsauto  ALL=(ALL)  NOPASSWD: ALL"
   - name: Deploy SSH Key
     authorized_key: user=opsauto
                     key="{{ lookup('file', '../ssh-keys/id_rsa.pub') }}"
                     state=present
   - name: Enable Password Authentication
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PasswordAuthentication'
           line="PasswordAuthentication yes"
           state=present
           backup=yes
     notify:
           - restart ssh
   - name: Disable Root Login
     lineinfile:
           dest=/etc/ssh/sshd_config
           regexp='^PermitRootLogin'
           line="PermitRootLogin no"
           state=present
           backup=yes
     notify:
       - restart ssh
   handlers:
   - name: restart ssh
     service:
       name=sshd
       state=restarted
